---
- name: Deploy Docker container to Azure VM
  hosts: azure_vm
  become: yes

  vars:
    docker_image: "{{ docker_username }}/green-vit:latest"
    port: "{{ port }}"
    mongo_url: "{{ mongo_url }}"

  tasks:
    - name: Pull latest Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop existing container (if running)
      community.docker.docker_container:
        name: green-vit
        state: stopped
      ignore_errors: yes

    - name: Remove old container (if exists)
      community.docker.docker_container:
        name: green-vit
        state: absent
      ignore_errors: yes

    - name: Run new container
      community.docker.docker_container:
        name: green-vit
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:{{ port }}"
        env:
          MONGO_URL: "{{ mongo_url }}"
          PORT: "{{ port }}"
