---
- name: Deploy Docker container to Azure VM
  hosts: web
  become: yes

  tasks:
    - name: Pull latest Docker image
      command: docker pull {{ lookup('env', 'DOCKER_USERNAME') }}/green-vit:latest

    - name: Stop existing container (if running)
      command: docker stop green-vit || true

    - name: Remove old container (if exists)
      command: docker rm green-vit || true

    - name: Run new container
      command: >
        docker run -d --name green-vit
        -p 80:{{ lookup('env', 'PORT') }}
        -e MONGO_URL={{ lookup('env', 'MONGO_URL') }}
        -e PORT={{ lookup('env', 'PORT') }}
        {{ lookup('env', 'DOCKER_USERNAME') }}/green-vit:latest
